### ISSUE TITLE
Blog is already stale

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/blog#14]
I think @marionettejs/marionette-core should consider either removing the blog, or having a regular release schedule and goals.  

Possibly reconsider having guest posters, or even repost, or having tl;dr posts linking to other useful blog posts out there.  

The blog should be some centralized useful, somewhat regularly updated place for all things marionette. 

This works fairly organically for the YouTube channel.  But the blog should try and utilize content that's already being created so it's less of a burden to keep things fresh.

**Comment by jdaudier** [comment]
@paulfalgout Yup, agreed. It was purposely abandoned since @jmeas didn't like how the blog generates a long URL and wasn't integrated with the site. 

Anyone up for the challenge of making the blog a part of the site somehow?

As for me, my philosophy is that good content trumps a perfect blog system.

Another option is not to have the blog but just have great guides. Either way, it means time devoted for writing content which I know is hard since everyone is busy and Sam hasn't given us our year-end bonuses yet. :grinning:

**Comment by jmeas** [comment]
> It was purposely abandoned since @jmeas didn't like how the blog generates a long URL and wasn't integrated with the site.

I hope there are other contributors to this other than me! Just because I won't make new content until the blog is a little bit more improved, but there are plenty of other folks who could be writing :)

**Comment by samccone** [comment]
:(
